### ISSUE TITLE
Missing CHATGPT_API KEY

### ISSUE THREAD

**Issue by kakamove6** [mattn/chatgpt#4]
I execute chatgpt ,receive the code MISSING CHARTGPT_API KEY

**Comment by mattn** [comment]
You need to get API key for ChatGPT.

https://platform.openai.com/overview

**Comment by ParsaGachkar** [comment]
I already have CHATGPT_API in my environment variables but still get this message

**Comment by ParsaGachkar** [comment]
never mind you were missing an "_" in output
```
Missing CHATGPT_API KEY
```
 i was expecting the name of variable to be CHATGPT_API based on your output upon observing your code just found out the variable's name should have been CHATGPT_API_KEY
